name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']  # Change to 'master' if that's your main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'  # Change to 'yarn' or 'pnpm' if you use those
      - name: Install dependencies
        run: npm install  # Change to yarn or pnpm if needed
      - name: Build
        run: npm run build  # Change to yarn or pnpm if needed
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
